[ FLAG_VAR.H
[ POLICE QUEST
[ By:  Greg Rowland and Jim Walls
[ For: Sierra On-Line Inc. 06/27/86
[ Last Update July 7, 1987AL



[ Local flags .........................................................
[ (use only in room logics; reset by room 0 init.logs)

%define	first.lf			220
%define	last.lf			239

%flag	lf0					220
%flag	lf1					221
%flag	lf2					222
%flag	lf3					223
%flag	lf4					224
%flag	lf5					225
%flag	lf6					226
%flag	lf7					227
%flag	lf8					228
%flag	lf9					229
%flag	lf10					230
%flag	lf11					231
%flag	lf12					232
%flag	lf13					233
%flag	lf14					234
%flag	lf15					235
%flag	lf16					236
%flag	lf17					237
%flag	lf18					238
%flag	lf19					239


[ Temp flags .........................................................
[ (use only in dynamic logics; reset by room 0 init.log)

%define	first.tf			240
%define	last.tf			255

%flag	tf0					240
%flag	tf1					241
%flag	tf2					242
%flag	tf3					243
%flag	tf4					244
%flag	tf5					245
%flag	tf6					246
%flag	tf7					247
%flag	tf8					248
%flag	tf9					249
%flag	tf10					250
%flag	tf11					251
%flag	tf12					252
%flag	tf13					253
%flag	tf14					254
%flag	tf15					255





[ Local Vars .........................................................
[(use only in room logics; reset by room 0 init.logs)

%define	first.lcl			220
%define	last.lcl			239

%var		lcl0					220
%var		lcl1					221
%var		lcl2					222
%var		lcl3					223
%var		lcl4					224
%var		lcl5					225
%var		lcl6					226
%var		lcl7					227
%var		lcl8					228
%var		lcl9					229
%var		lcl10				230
%var		lcl11				231
%var		lcl12				232
%var		lcl13				233
%var		lcl14				234
%var		lcl15				235
%var		lcl16				236
%var		lcl17				237
%var		lcl18				238
%var		lcl19				239
												  

[ Temp Vars ........................................................
[(use only in dynamic logics; reset by room 0 init.log)

%define	first.tmp			240
%define	last.tmp			255

%var		tmp0					240
%var		tmp1					241
%var		tmp2					242
%var		tmp3					243
%var		tmp4					244
%var		tmp5					245
%var		tmp6					246
%var		tmp7					247
%var		tmp8					248
%var		tmp9					249
%var		tmp10				250
%var		tmp11				251
%var		tmp12				252
%var		tmp13				253
%var		tmp14				254
%var		tmp15				255

