[ POLICE QUEST
[ rm108.cg
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. September 1, 1987
[ Last Update September 1, 1987al

[ Stop Peddling Suspect


%include "gamedefs"
[%include "rm108.msg"


get.posn( a.suspect, x, y);

if ((tempX != x || tempY != y))
	{
	tempX = x;
	tempY = y;
	start.cycling( a.suspect);
	}
else
	{
	if (keepCyclingSuspect)
		{
		start.cycling( a.suspect);
		}
	else
		{
		stop.cycling( a.suspect);
		}
	}


