[ POLICE QUEST
[ rm112.msg
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. 9/2/86
[ Last Update September 25, 1987al

[ lgc.computer


[			"1234567890123456789012		Maximum line length.
%message	1	"_"
%message	2	"<"
%message	3	"COMPUTER DOWN."
%message	4	"No record for input."
%message	5	"45 caliber,"
%message	6	"automatic handgun"
%message	7	"serial #SW9764912"
%message	8	"reported stolen."
%message	9	"Chicago, 12/4/86"
%message	10	"Contact Det. Taber at"
%message	11	"CPD, 1 (312) 555-3382"
%message	12	"555-6537,"
%message	13	"unlisted number"
%message	14	"Leroy Pierson"
%message	15	"1037 Grove St."
%message	16	"Apt #334,"
%message	17	""
%message	18	"Lytton, CA"
%message	19	"Delphoria Hotel"
%message	20	"Jason Taselli"
%message	21	"FED Warrant: 123-1985"
%message	22	"Alias: Marvin Hoffman"
%message	23	"5'11\", 195', blk/brn"
%message	24	"Tattoo of flower"
%message	25	"above left nipple."
%message	26	"1985 Motorcycle 750"
%message	27	"Color: cherry red"
%message	28	"Stolen: %m18"
%message	29	"License: M65789"
%message	30	"VIN: M09876543"
%message	31	"459PC Burglary"
%message	32	".22-cal. lever-action"
%message	33	"Ramington rifle"
%message	34	"oak stock, gold trig."
%message	35	"Serial #R12345678"
%message	36	"Still outstanding:"
%message	37	"Contact Lytton PD"
%message	38	"Record not on file."
%message	39	"Victim:"
%message	40	"Fancy Pants Lingerie"
%message	41	"57 pair silk skivvies"
%message	42	"Blue, size 46-50,"
%message	43	"Zippered crotch"
%message	44	"Suspect:"
%message	45	"Short Fat Fanny"
%message	46	"2400 lbs Dog Feed"
%message	47	"Fat Fred's Feed Farm"
%message	48	"9 Large-mouth Belly"
%message	49	"Bustin' Stink Baits"
%message	50	"\"Chink's Cast N"
%message	51	"Catchit\" Bait Store"
%message	52	"Missing dog:"
%message	53	"Name of Big Dog"
%message	54	"AKA \"The Consumer\""
%message	55	"3', 115 lbs, blk/wht"
%message	56	"Approach with caution"
%message	57	"is very affectionate"
%message	58	"with uniformed police"
%message	59	"officers."
%message	60	"8 diamond wedding"
%message	61	"rings."
%message	62	"Jessie the Jeweler"
%message	63	"Marvin Hoffman"
%message	64	"Ill. DDL #A472457"
%message	65	"2231 W 104th St"
%message	66	"Chicago, Illinois"
%message	67	"5'11\",195lbs,blk/brn"
%message	68	"DOB: 3/1/39"
%message	69	"1983 Cadillac deVille"
%message	70	"Color: black"
%message	71	"Stolen, %m18"
%message	72	""
%message	73	"License: LOP1238"
%message	74	"VIN: C03456218"
%message	75	"Registered owner:"
%message	76	"Malcolm Washington"
%message	77	"234 W Center St"
%message	78	""
%message	79	"Biologic intercourse."
%message	80	"Anal release of an"
%message	81	"elastic fluid."
%message	82	"Solid waste matter"
%message	83	"from the bowels."
%message	84	"A yellowish fluid"
%message	85	"secreted by the"
%message	86	"kidneys, passed"
%message	87	"through ureters to"
%message	88	"bladder, from which"
%message	89	"it is discharged"
%message	90	"through the urethra."
%message	91	"Any port in a storm!"
%message	92	"Found on a male."
%message	93	"Freddie Justinfletch"
%message	94	"Alias:"
%message	95	"Freddie the Freak"
%message	96	"Physical:"
%message	97	"5'3\",219lbs,bald/grn"
%message	98	"Wanted for:"
%message	99 	"purse snatching"
%message	100	"assault and battery"
%message	101	"narcotics violations"
%message	102	"James Jenkins"
%message	103	"Jimmy \"the Junky\""
%message	104	""
%message	105	"6'4\",160lbs,blk/brn"
%message	106	"Francis Malone"
%message	107	"Short Fat Fanny"
%message	108	"4'9\",160lbs,blk/blu"
%message	109	"WAR: Q72, petty theft"
%message	110	"Winiford Watson"
%message	111	"Winnie the Weasel"
%message	112	"5'8\",180lbs,bald/brn"
%message	113	"Numerous tattoos."
%message	114	"Narcotics, weapons,"
%message	115	"and armed robbery"
%message	116	"violations."
%message	117	"555-6537"
%message	118	"555-4369"
%message	119	"unlisted telephone"
%message	120	"number of: Police"
%message	121	"Commissioner Hacker"
%message	122	"Enter search string:"
%message	123	"Lytton Police Dept."
%message	124	 "On-Line Database"
%message	125	   "Good morning!"
%message	126	"Didn't match %s1."		[	This is for the logfile.
%message	127	"Former programmer;"
%message	128	"author of that cult"
%message	129	"classic, \"Bop-A-Bet!\""
%message	130	"Computer renaissance"
%message	131	"man: artist, program-"
%message	132	"mer, guitarist."
%message	133	"Nice ol' family man;"
%message	134	"former CHiP (not as"
%message	135	"in cow)."
%message	136	"Like a civil servant:"
%message	137	"we can't fire him and"
%message	138	"can't get him to work"
%message	139	"15-year veteran, LPD"
%message	140	"Helen Hots"
%message	141	"202 Gyrate Ct,"
%message	142	"License: OHMYMG"
%message	143	"On-Line Help is no"
%message	144	"longer available."
%message	145	"ohmymg"
%message	146	"dir"
%message	147	"BDOS err on a:"
%message	148	"convicted drug pusher"
%message	149	"al lowe"
%message	150	"greg rowland"
%message	151	"jim walls"
%message	152	"ken williams"
%message	153	"Wanted for murder,"
%message	154	"drug involvement,"
%message	155	"prostitution."
%message	156	"Last seen area of"
%message	157	"Chicago, Ill."
%message	158	"prgrmr1"
%message	159	"Art Serabian,"
%message	160	"No wants."
%message	161	"m65789"				[	CA license yamama cycle
%message	162	"m09876543"			[	VIN # yamama cycle
%message	163	"r12345678"			[	Ramington rifle
%message	164	"sw9764912"			[	Taselli/hoffman stolen handgun
%message	165	"lop1238"				[	TH's license # when car stolen (car black)
%message	166	"c03456218"			[	Taselli/hoffman's car vin #
%message	167	"ul6942"				[	TH's license # when captured (car blue)
%message	168	"License: UL6942"
%message	169	"Issued to:"
%message	170	"1979 Cadillac,"
%message	171	"junked in 1983."
%message	172	"VIN: C0864213579"
%message	173	"C0864213579"			[	VIN of junked caddie, lic#UL6942
%message	174	"hots"
%message	175	""
%message	176	""
%message	177	""
%message	178	""
%message	179	""


[	hoffman
[	martinez
[	paxton
[	washington			[	reported stolen vehicle, LOP1238
[	west
