[ POLICE QUEST
[ rm4.h
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. 7/22/87
[ Last Update September 7, 1987al

[ common for squad room and briefings.



%object	a.cop1			1
%object	a.cop2			2
%object	a.cop3			3
%object	a.cop4			4
%object	a.cop5			5
%object	a.cop6			6
%object	a.cop7			7
%object	a.paper			10

						
%define	moving0			lcl0
%define	moving1			lcl1
%define	moving2			lcl2
%define	moving3			lcl3
%define	moving4			lcl4
%define	moving5			lcl5
%define	moving6			lcl6
%define	cop0				lcl7
%define	cop1				lcl8
%define	cop2				lcl9
%define	cop3				lcl10
%define	cop4				lcl11
%define	cop5				lcl12
%define	cop6				lcl13
%define	cop7				lcl14
%define	briefTimer		lcl15

%define	work11			tmp0
%define	work12			tmp1
%define	work13			tmp2
%define	work14			tmp3
%define	Strikes			tmp15

						
%define	moved0			lf0
%define	moved1			lf1
%define	moved2			lf2
%define	moved3			lf3
%define	moved4			lf4
%define	moved5			lf5
%define	moved6			lf6
%define	conver0			lf7
%define	conver1			lf8
%define	conver2			lf9
%define	conver3			lf10
%define	conver4			lf11
%define	conver5			lf12
%define	conver6			lf13
%define	conver7			lf14
%define	your.seat			lf15
%define	dooley.yell		lf16
%define	envelope.open		lf17
%define	lookInMyBox		lf18
%define	heMissedBrief1		lf19

%define	nearSeat			tf0
%define	nearHole1			tf1
%define	nearHole2			tf2
%define	nearHole3			tf3
%define	nearHole4			tf4
%define	nearTables		tf5
%define	nearDrawers		tf6
%define	conver8			tf7
%define	readyForBriefing	tf8

