[ POLICE QUEST
[ rm40.h
[ By:  Greg Rowland and Jim Walls
[ For: Sierra On-Line Inc. 3/10/87
[ Last Update October 10, 1987al


[	formerly "jail defs"



%define	moved0			lf0
%define	moved1			lf1
%define	moved2			lf2
%define	conver0			lf3
%define	conver1			lf4
%define	conver2			lf5
%define	conver3			lf6
%define	conver4			lf7
%define	conver5			lf8
%define	dockedForGun		lf9
%define	nearJack			lf10
%define	nearLaura			lf11
%define	nearJailer		lf12
%define	nearSuspect		lf13
%define	nearBCrusher		lf14
%define	MiddleOfFrontRoom	lf15
%define	nearDoor			lf16
%define	nearSC			lf17

%define	door.work			tf0
%define	door.open			tf1
%define	actor.using.door	tf2
%define	following			tf3
%define   start.scene		tf4
%define	egok				tf5


%define	moving0			lcl0
%define	moving1			lcl1
%define	moving2			lcl2
%define	jailerX			lcl3
%define	jailerY			lcl4
%define	simms.x			lcl5
%define	simms.y			lcl6

	
%object	a.bigsam				1	[jailer
%object	a.jack				2	[back up officer while booking taselli
%object	a.simms				3	[drug bust
%object	a.laura				4
%object	a.bone.crusher			5	[bone.crusher 
%object	a.booking.door.open		6
%object	a.booking.door.closed	7
%object	a.cell.door			8
%object	aKiss				9
%object	a.sweet.cheeks			10
%object	a.jailer				11

