[ POLICE QUEST
[ rm5.h
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. 7/22/87
[ Last Update August 30, 1987al



[ common defines for locker room


%object	a.cop1			1
%object	a.cop2	 		2
%object	a.cop3			3
%object	a.fudley			4
%object	a.towel			5
%object	a.shower			6
%object	a.janitor			7
%object	a.sonny.shower		8
%object	aPants			9



[%var 	locker.scene		48
	%define	beforeBrief1		0
	%define	janitor1			10
	%define	beforeBrief2		20
	%define	janitor2			30
	%define	janitor3			40
	%define	sawPimpSuit		50


%define	moving0			lcl0
%define	moving1			lcl1
%define	moving2			lcl2
%define	moving3			lcl3
%define	rinseStatus		lcl4
%define	cop1				lcl5
%define	cop2				lcl6
%define	cop3				lcl7
%define	fudley 			lcl8
[%define	lcl9
%define	msg1				lcl10
%define	msg2				lcl11
%define	msg3				lcl12
%define	msg4				lcl13


%define	moved0			lf0
%define	moved1			lf1
%define	moved2			lf2
%define	moved3			lf3
%define	conver0			lf4
%define	conver1	  		lf5
%define	conver2			lf6
%define	conver3			lf7
%define	conver4			lf8
%define	leftShowerOn		lf9
%define	nearToilet		lf10
%define	conver6			lf11
%define	inShower			lf12
%define	dressed			lf13
%define	towel			lf14
%define	in.locker			lf15
%define	turnShowerOn		lf16
%define	turnShowerOff		lf17
%define	inShowerWithFudley	lf18
%define	conver5			lf19
