[ POLICE QUEST
[ rm77.msg
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. 6/9/86
[ Last Update August 11, 1987al

[	middle stair room in hotel


%message	1
"You cautiously follow \"Mr. Jessie Bains\" up the flight of stairs."

%message	2
"An interesting manuever on your part has separated you from your suspect.
 Now what will you do?"

