[ POLICE QUEST
[ rm8.msg
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. 6/9/86
[ Last Update August 30, 1987al

[ glove box

[			"12345678901234		is the max length for a license
%message	1	"Marvin Hoffman"
%message	2	"Male 6'0 194'"
%message	3	"HAIR Black"
%message	4	"EYES Blue"
%message	5	"DOB 6/2/56"
%message	6	"31 W 104th St"
%message	7	"Chicago, IL"
%message	8	"RESTRICTIONS"
%message	9	"None."

[			"12345678901234		is the max length for a license
%message	10	"Leroy Pierson"
%message	11	"Male 5'10 187'"
%message	12	"HAIR Black"
%message	13	"EYES Blue"
%message	14	"DOB 4/28/55"
%message	15	"1134 Beach St"
%message	16	"Newport, CA"




%message	20
"You open the note book."

%message	21
"Your partner will impound these items into evidence, along with the car."

%message	22
"You observe a black notebook, and two driver's licenses."

