[ POLICE QUEST
[ roomnums.h
[ By:  Greg Rowland, Jim Walls and Al Lowe
[ For: Sierra On-Line Inc. 3/10/86
[ Last Update September 20, 1987al


[	This list of room numbers was formerly an INCLUDE file, but now is
[merely for reference purposes.



%define	rm.title					1
%define	lgc.ego					2	[	ego gun logics
%define	rm.tits					3		
%define	rm.squad					4		
%define	rm.locker					5		
%define	rm.hqhall1				6		
%define	rm.yard					7		
%define	rmGloveBox				8
%define	rm.trunk					9		
%define	rm.map10					10		
%define	rm.map11					11		
%define	rm.map12					12		
%define	rm.map13					13
%define	rm.map14					14
%define	rm.map15					15
%define	rm.map16					16
%define	rm.map17					17
%define	rm.map18					18
%define	rm.map19					19
%define	rm.map20					20
%define	rm.map21					21
%define	rm.map22					22
%define	rm.map23					23
%define	rm.map24					24
%define	rm.map25					25
%define	rmMurder					26
%define	lgc.freeway1				27		[fw rms 22, 16
%define	lgc.freeway2				28		[fw rms 19, 13
%define	lgc.janitor				29
%define	rm.foxstop				30
%define	rm.drunkstop				31
%define	rm.felony					32
%define	rm.blue.enter				33
%define	rm.blue.room				34
%define	rm.caffine.entrance			35
%define	rm.caffine.inside			36
%define	rm.biker.bar				37
%define	lgc.briefcase				38
%define	lgc.lockerm				39
%define	rm.jail					40
%define	rm.jail.yard				41
%define	rm.srgoff					42
%define	rm.moroff					43
%define	lgc.brief1				44
%define	lgc.brief2				45
%define	lgc.squadrm				46
%define	rmInsideLocker				47
%define	lgc.bartender				48
%define	rm.narcoff				49
%define	lgc.clipboard				50
%define	rm.teletype				51
%define	rm.hqhall2				52
%define	rm.court.house				53
%define	rm.court.hall				54
%define	rm.court.room				55
%define	rm.park.entrance			56
%define	rm.park.scene				57
%define	lgcJailDdrunk				58	[	jail dyns
%define	lgcJailTaselli				59
%define	rm.cotton.cove				60
%define	lgcJailColbyS				61
%define	lgcJailCheeks				62
%define	rm.hotel					63	[	Hotel Delphoria
%define	rm.lobby					64
%define	rm.HotelHall				65
%define	rm.HotelElev				66
%define	rm.209					67
%define	rm.cocktail				68
%define	rm.storage				69
%define	rm.casino					70
%define	rm.gamble					71
%define	rmRights					72
%define	lgcCheeks					73
%define	lgcHotelText				74
%define	rm.poker.game				75
%define	rmStairTop				76
%define	rmStairMid				77
%define	rmStairBot				78
%define	rm.bains					79
%define	lgcResidential				80

[Poker dynamics are 81-91.

%define	lgcCommercial				92
%define	lgcOceanFrontage			93
%define	lgc.stopped.cars			94
%define	lgc.traffic.stop			95
%define	lgc.carRadio				96
%define	lgcMorgan1				97
%define	lgc.error					98
%define	lgc.debug					99
%define	lgc.rm0.init.log    		100
%define	lgc.startup				101
%define	lgc.help					102
%define	rmWinner1					103
%define	rmWinner2					104
%define	lgc.trace					105
%define	lgc.QA					106
%define	lgc.scene					107
%define	lgc.suspect.pedaling		108
%define	lgc.phone					109	[	Generic Telephone logics
%define	lgc.filedrawer				110	[	rm.narcoff
%define	lgc.file					111	[	rm.narcoff folder interiors
%define	lgc.computer				112	[	rm.12, rm.teletype
%define	lgc.blackbook				113	[evidence cage rm.6, rm.hqhall1
%define	lgc.SupectGun				114
%define	lgcBumperCars				115
%define	lgc.lytton.news    			116	[	squad room
%define	lgc.car					117	[	generic carinit logs
%define	lgc.suspect				118	[currrent.suspect gun/death logics
%define	lgc.suspect.vehicle			119	[	current.suspect driving

